/*
 * Hoofdscherm.java
 *
 * Created on 24 maart 2010, 11:49
 */
package view;

import component.Database;
import javax.swing.JOptionPane;

/**
 *
 * @author  Robin
 */
public class Hoofdscherm extends javax.swing.JFrame {

    /** Creates new form Hoofdscherm */
    public Hoofdscherm() {
        initComponents();
        if (!Database.openConnection("sportivo", "root", "120938")) {

            JOptionPane.showMessageDialog(null, "Geen verbinding met de database!");
            System.exit(0);
        }        
        
    }
    public String vulLijst(String vulLijst) {
        return vulLijst;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWijzig = new javax.swing.JButton();
        btnVerwijder = new javax.swing.JButton();
        btnZoek = new javax.swing.JButton();
        btnAanmaken = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        tfZoek = new javax.swing.JTextField();
        btnSportweek = new javax.swing.JButton();
        btnDocent = new javax.swing.JButton();
        btnDeelnemers = new javax.swing.JButton();
        btnSport = new javax.swing.JButton();
        btnCursus = new javax.swing.JButton();
        btnBetaling = new javax.swing.JButton();
        lblLayOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sportivo Database");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWijzig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knop3.png"))); // NOI18N
        btnWijzig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnWijzig.setContentAreaFilled(false);
        btnWijzig.setFocusPainted(false);
        btnWijzig.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knop3_a.png"))); // NOI18N
        btnWijzig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWijzigActionPerformed(evt);
            }
        });
        getContentPane().add(btnWijzig, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        btnVerwijder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knop2.png"))); // NOI18N
        btnVerwijder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnVerwijder.setContentAreaFilled(false);
        btnVerwijder.setFocusPainted(false);
        btnVerwijder.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knop2_a.png"))); // NOI18N
        btnVerwijder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerwijderActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerwijder, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        btnZoek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knop4.png"))); // NOI18N
        btnZoek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnZoek.setContentAreaFilled(false);
        btnZoek.setFocusPainted(false);
        btnZoek.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knop4_a.png"))); // NOI18N
        btnZoek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoekActionPerformed(evt);
            }
        });
        getContentPane().add(btnZoek, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, -1, -1));

        btnAanmaken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knop.png"))); // NOI18N
        btnAanmaken.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAanmaken.setContentAreaFilled(false);
        btnAanmaken.setFocusPainted(false);
        btnAanmaken.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knop_a.png"))); // NOI18N
        btnAanmaken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAanmakenActionPerformed(evt);
            }
        });
        getContentPane().add(btnAanmaken, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Olympische logo2.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        tfZoek.setText("Zoek...");
        getContentPane().add(tfZoek, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 70, 120, -1));

        btnSportweek.setBackground(new java.awt.Color(255, 255, 255));
        btnSportweek.setFont(new java.awt.Font("Verdana", 1, 15));
        btnSportweek.setText("sportweken");
        btnSportweek.setAlignmentY(0.0F);
        btnSportweek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSportweek.setFocusPainted(false);
        btnSportweek.setIconTextGap(0);
        btnSportweek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSportweekActionPerformed(evt);
            }
        });
        getContentPane().add(btnSportweek, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 30));

        btnDocent.setBackground(new java.awt.Color(255, 255, 255));
        btnDocent.setFont(new java.awt.Font("Verdana", 1, 15));
        btnDocent.setText("docenten");
        btnDocent.setAlignmentY(0.0F);
        btnDocent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnDocent.setFocusPainted(false);
        btnDocent.setIconTextGap(0);
        btnDocent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocentActionPerformed(evt);
            }
        });
        getContentPane().add(btnDocent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 30));

        btnDeelnemers.setBackground(new java.awt.Color(255, 255, 255));
        btnDeelnemers.setFont(new java.awt.Font("Verdana", 1, 15));
        btnDeelnemers.setText("deelnemers");
        btnDeelnemers.setAlignmentY(0.0F);
        btnDeelnemers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnDeelnemers.setFocusPainted(false);
        btnDeelnemers.setIconTextGap(0);
        btnDeelnemers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeelnemersActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeelnemers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        btnSport.setBackground(new java.awt.Color(255, 255, 255));
        btnSport.setFont(new java.awt.Font("Verdana", 1, 15));
        btnSport.setText("sporten");
        btnSport.setAlignmentY(0.0F);
        btnSport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSport.setFocusPainted(false);
        btnSport.setIconTextGap(0);
        btnSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSportActionPerformed(evt);
            }
        });
        getContentPane().add(btnSport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, 30));

        btnCursus.setBackground(new java.awt.Color(255, 255, 255));
        btnCursus.setFont(new java.awt.Font("Verdana", 1, 15));
        btnCursus.setText("cursussen");
        btnCursus.setAlignmentY(0.0F);
        btnCursus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCursus.setFocusPainted(false);
        btnCursus.setIconTextGap(0);
        btnCursus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursusActionPerformed(evt);
            }
        });
        getContentPane().add(btnCursus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 110, 30));

        btnBetaling.setBackground(new java.awt.Color(255, 255, 255));
        btnBetaling.setFont(new java.awt.Font("Verdana", 1, 15));
        btnBetaling.setText("betalingen");
        btnBetaling.setAlignmentY(0.0F);
        btnBetaling.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnBetaling.setFocusPainted(false);
        btnBetaling.setIconTextGap(0);
        btnBetaling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetalingActionPerformed(evt);
            }
        });
        getContentPane().add(btnBetaling, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 110, 30));

        lblLayOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLayOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background2.png"))); // NOI18N
        lblLayOut.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblLayOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnSportweekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSportweekActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnSportweekActionPerformed

    private void btnDocentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocentActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnDocentActionPerformed

    private void btnDeelnemersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeelnemersActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnDeelnemersActionPerformed

    private void btnSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSportActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnSportActionPerformed

    private void btnCursusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursusActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnCursusActionPerformed

    private void btnBetalingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetalingActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_btnBetalingActionPerformed

    private void btnAanmakenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAanmakenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAanmakenActionPerformed

    private void btnWijzigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWijzigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWijzigActionPerformed

    private void btnVerwijderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerwijderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerwijderActionPerformed

    private void btnZoekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnZoekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Hoofdscherm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAanmaken;
    private javax.swing.JButton btnBetaling;
    private javax.swing.JButton btnCursus;
    private javax.swing.JButton btnDeelnemers;
    private javax.swing.JButton btnDocent;
    private javax.swing.JButton btnSport;
    private javax.swing.JButton btnSportweek;
    private javax.swing.JButton btnVerwijder;
    private javax.swing.JButton btnWijzig;
    private javax.swing.JButton btnZoek;
    private javax.swing.JLabel lblLayOut;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField tfZoek;
    // End of variables declaration//GEN-END:variables
}
